In [2]:
import os
import sys

import numpy as np
import torch
from torch.utils.data.dataloader import DataLoader
from torch.utils.data.dataset import TensorDataset

from hw2.all_cnn import all_cnn_module
from hw2.preprocessing import cifar_10_preprocess

import torch.optim as optim
import torch.nn.functional as F

import torch.nn as nn

#pred = []

In [2]:
#a = np.random.random((10,10))
#print (np.mean(a,1, keepdims= True))

In [3]:
# Load my dataset here
def myDataset():
    
    batch_size = 32
    
    x = np.load(os.path.join('train_feats.npy')).astype(float)
    y = np.load(os.path.join('train_labels.npy'))
    #print(type(x[0]),x[1].shape)
    xTst= np.load(os.path.join('test_feats.npy'))
    #yTst = np.zeros((xTst.shape[0],), dtype=y.dtype)
    
    val = 1000
#     print (np.mean(x,1,keepdims=True))
    x, xTst = cifar_10_preprocess(x, xTst)    
 
    
    
    train_loader = DataLoader(TensorDataset(torch.from_numpy(x).float(), torch.from_numpy(y).long()),
                              batch_size = batch_size, shuffle=True)
    #val_loader = DataLoader(TensorDataset(torch.from_numpy(xval).float(), torch.from_numpy(yval).long()),
     #                       batch_size = batch_size, shuffle=True)
    test_loader = DataLoader(TensorDataset(torch.from_numpy(xTst).float(), torch.from_numpy(xTst).long()),
                            batch_size = 1, shuffle=False)
                
    return train_loader, train_loader , test_loader

In [4]:
d, f, g = myDataset()

In [5]:


def write_results(model, x):

    
    model.eval()
    
    with open('predictions.txt', 'w') as f:
        for x in predictions:
            if torch.cuda.is_available():
                x = x.cuda()
            prd = torch.max(model(x), 1)[1].data.cpu().numpy()
            for y in prd:
                f.write("{}\n".format(np.asscalar(y)))

In [6]:
def main(argv):
    
    #initalize functions
    model = all_cnn_module()
    epochs = 20
    
    trainXt, valXt, testXt = myDataset()
    
    #define loss function values 
    #optimizer = optim.SGD(model.parameters(), lr=0.00001, momentum=0.9,weight_decay = 0.001)
    
    optimizer = optim.Adam(model.parameters(), lr=0.0001)
    
    criterion = nn.CrossEntropyLoss()
    
    if torch.cuda.is_available():
        model.cuda()
    
    #model.load_state_dict(torch.load("model.pt"))
    
    model.train()
    
    for epochs in range(epochs):
        
        # Train
        losses = []
        
        for (inputs, labels) in (trainXt):
            
            if torch.cuda.is_available():
                inputs = inputs.cuda()
                labels = labels.cuda()
                criterion = criterion.cuda()
                
                
            inputs = torch.autograd.Variable(inputs)
            labels = torch.autograd.Variable(labels)
            #print(labels)
            
            
            optimizer.zero_grad()
            
            #inputs = np.float32(inputs)
            
            #inputs = inputs.float32
            
            #print('Type', type(inputs))
    
            outputs = model(inputs)
            loss = criterion(outputs, labels)
            loss.backward()
            optimizer.step()
            losses.append(loss.cpu().detach().numpy())
            
        torch.save(model.state_dict(), 'model.pt')
            
        print(" the error ",np.mean(losses))
            
        print(" Training done")
        
            
    for epochs in range(2):
            
        for (inputs, labels) in (testXt):
            
            if torch.cuda.is_available():
                inputs = inputs.cuda()
                
            inputs = torch.autograd.Variable(inputs)
            
            pred  = model(inputs)
            #pred = pred.cpu()
            
        np.savetxt('submission.csv', pred, delimiter=',')
                
        write_results(model, pred)

In [7]:
if __name__ == '__main__':
    main(sys.argv[1:])

 the error  2.160431
 Training done
 the error  1.6514697
 Training done
 the error  1.4866111
 Training done
 the error  1.3782543
 Training done
 the error  1.2757906
 Training done
 the error  1.1857789
 Training done
 the error  1.1321837
 Training done
 the error  1.0829896
 Training done
 the error  1.043538
 Training done
 the error  0.99852794
 Training done
 the error  0.9574708
 Training done
 the error  0.9242283
 Training done
 the error  0.88963
 Training done
 the error  0.8573669
 Training done
 the error  0.82447654
 Training done
 the error  0.7955723
 Training done
 the error  0.77138364
 Training done
 the error  0.74527097
 Training done
 the error  0.7215173
 Training done
 the error  0.7034988
 Training done


RuntimeError: Can't call numpy() on Variable that requires grad. Use var.detach().numpy() instead.

In [18]:
trainXt, valXt, testXt = myDataset()

epochs = 20

savedOut = []

model = all_cnn_module()

if torch.cuda.is_available():
        model.cuda()
    
model.load_state_dict(torch.load("model.pt"))

#for epochs in range(epochs):            
for (inputs, labels) in (testXt):

    if torch.cuda.is_available():
        inputs = inputs.cuda()

    inputs = torch.autograd.Variable(inputs)

    pred  = model(inputs)

    #m = torch.max(model(inputs), 1)[1].data.cpu().numpy()

    pred = np.argmax(pred.cpu().detach().numpy(),1)

    savedOut.append(np.rint(pred))

    #pred.data.cpu().numpy()
    #torch.max(model(x), 1)[1].data.cpu().numpy()

#np.savetxt('predictions.txt', pred)

#np.savetxt('pred.txt', m)

#write_results(model, pred)

In [19]:
savedOut

[array([7.]),
 array([1.]),
 array([1.]),
 array([6.]),
 array([7.]),
 array([8.]),
 array([6.]),
 array([8.]),
 array([5.]),
 array([7.]),
 array([2.]),
 array([1.]),
 array([9.]),
 array([0.]),
 array([5.]),
 array([9.]),
 array([1.]),
 array([6.]),
 array([9.]),
 array([9.]),
 array([8.]),
 array([6.]),
 array([6.]),
 array([1.]),
 array([9.]),
 array([1.]),
 array([0.]),
 array([0.]),
 array([6.]),
 array([6.]),
 array([0.]),
 array([4.]),
 array([3.]),
 array([3.]),
 array([5.]),
 array([3.]),
 array([6.]),
 array([4.]),
 array([9.]),
 array([4.]),
 array([7.]),
 array([1.]),
 array([3.]),
 array([9.]),
 array([7.]),
 array([5.]),
 array([3.]),
 array([4.]),
 array([2.]),
 array([9.]),
 array([9.]),
 array([1.]),
 array([8.]),
 array([9.]),
 array([1.]),
 array([6.]),
 array([8.]),
 array([0.]),
 array([5.]),
 array([5.]),
 array([9.]),
 array([5.]),
 array([5.]),
 array([8.]),
 array([3.]),
 array([3.]),
 array([9.]),
 array([7.]),
 array([2.]),
 array([4.]),
 array([6.]),
 array

In [12]:
round(savedOut, 0)

#savedOut.astype(int)

TypeError: type list doesn't define __round__ method

In [8]:
np.savetxt('predictions.txt', savedOut)

In [ ]:
def write_results(predictions, output_file='predictions.txt'):
    """
    Write predictions to file for submission.
    File should be:
        named 'predictions.txt'
        in the root of your tar file
    :param predictions: iterable of integers
    :param output_file:  path to output file.
    :return: None
    """
    with open(output_file, 'w') as f:
        for y in predictions:
            f.write("{}\n".format(y))
